[build]
  # 安装依赖并在 client 目录中构建 Storybook
  command = "cd client && npm install && npm run build-storybook"
  # 构建产物目录
  publish = "client/storybook-static"

# 可选：环境变量（如需要 Netlify Functions）
#[context.production.environment]
#  NODE_ENV = "production" 