name: Storybook CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Check environment
        run: |
          node -v
          npm -v
          echo "Free disk space:"
          df -h
          echo "Memory info:"
          free -h

      - name: List Storybook directory
        run: |
          ls -la client/.storybook

      - name: Install dependencies
        working-directory: ./client
        run: |
          npm ci
          echo "Installed dependencies:"
          npm list --depth=0 | grep storybook

      - name: Fix Storybook path issues
        working-directory: ./client
        run: |
          # 修复Windows路径分隔符问题
          sed -i 's/\\\\/\//g' .storybook/main.js
          cat .storybook/main.js

      - name: Build Storybook
        working-directory: ./client
        env:
          HUSKY: '0'
          NODE_OPTIONS: '--max_old_space_size=8192'
          CI: 'true'
        run: |
          # 保存详细日志以便调试
          npm run build-storybook --loglevel=verbose > build-output.log 2>&1 || {
            echo "===== BUILD FAILED! ====="
            echo "Last 100 lines of build log:"
            tail -n 100 build-output.log
            echo "===== DETAILED ERROR INFO ====="
            grep -A 10 -B 5 "ERR!" build-output.log || true
            echo "Package versions:"
            npm list --depth=0
            exit 1
          }

      - name: Upload Storybook Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: client/storybook-static 